version: '3.9'
services:
    anthropic-fastapi:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: anthropic-fastapi
        hostname: anthropic-fastapi
        image: anthropic-fastapi
        volumes:
            - .:/anthropic-fastapi
        ports:
            - "8000:8000"
        restart: always